name: ReleasePR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number triggered'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Extract ref
        uses: actions/github-script@v4
        id: extract-ref
        with:
          script: |
            const prNumber = '${{ github.event.inputs.pr_number }}'
            return prNumber === '' ? context.ref : `refs/pull/${prNumber}/head`
          result-encoding: string

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
          ref: ${{ steps.extract-ref.outputs.result }}

      - name: Add GiHub Package Token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN_TEST }}" > ~/.npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Packages
        run: npm install

      - name: Build Lib
        run: npm run build

      - name: Set Variables
        id: vars
        run: |
          echo "::set-output name=github_short_sha::$(git rev-parse --short HEAD | cut -c1-7)"

      - name: Deploy new Package
        run: |
          npm version v${{ env.TAG }} --no-git-tag-version
          npm publish --tag ${{ env.TAG }}
        env:
          TAG: 0.0.0-rc.${{ steps.vars.outputs.github_short_sha }}
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN_TEST }}

      - name: Notify to PR Comment
        if: steps.extract-ref.outputs.result != 'refs/heads/master'
        uses: actions/github-script@v4
        with:
          script: |
            await github.issues.createComment({
              ...context.repo,
              issue_number: ${{ github.event.inputs.pr_number }},
              body: 'NPM Published! Do `npm i tsds@${{ steps.vars.outputs.github_short_sha }}`',
            })
